In [2]:
## 00. Pytorch fundamentals



In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

1.13.1+cu116


## introduction to tensors

###creating tensors


In [2]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.item()

7

In [5]:
#vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
#matrix
MATRIX = torch.tensor([[7,8],[9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[1]

tensor([ 9, 10])

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
#Tensor
TENSOR = torch.tensor([[[1,2,3], [3,6,9], [2,5,4]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 5, 4]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

In [15]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 5, 4]])

###Random tensors
 why random tensors?

 they are important beacause the way neurl network learn is that they start with tensors full of random numbers and then adjust those random numnes to better represent the data

 `Start with random numbers -> look at data -> update random numbers -> look at data -> update ranodm numbers

In [16]:
#Create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor


tensor([[0.3718, 0.5799, 0.5751, 0.7020],
        [0.3898, 0.9110, 0.3723, 0.6855],
        [0.0144, 0.7050, 0.8547, 0.0949]])

In [17]:
random_tensor.ndim

2

In [19]:
#create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224)) # height, width, color channels(r,g,b)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

###Zeros and ones

In [22]:
#Create a tensor aof all zeros
zeros = torch.zeros(size=(3,4))
zeros


tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [24]:
#create a tensor of ones
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [29]:
ones.dtype

torch.float32

In [30]:
random_tensor.dtype

torch.float32

Create a range of tensors and tensors like

In [37]:
#Use torch.arange()
one_to_ten = torch.arange(start=1,end=11, step=1)
one_to_ten


tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
#Creating tensors-like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Tensor datatypes

tensor datatypes is one of the 3 big errors you'll run into with pytorch and deep learning.

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [55]:
#Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],dtype=None, device=None, requires_grad=False) #whether or not to track the gradient
float_32_tensor

tensor([3., 6., 9.])

In [56]:
float_32_tensor.dtype

torch.float32

In [57]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [58]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [59]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [61]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

Getting information from tensors

Tensors not right datatype - to do get datatype from a tensor,  can use 'tensor.dtype'
Tensors not right shape - to get shape from a tensor, can use 'tensor.shape'
Tensors not on the right device-  to get device from a tensor, can use 'tensor.device'

In [62]:
#Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.1796, 0.1926, 0.5117, 0.1675],
        [0.3251, 0.9878, 0.7469, 0.7309],
        [0.5965, 0.8890, 0.7639, 0.0113]])

In [63]:
#Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")

tensor([[0.1796, 0.1926, 0.5117, 0.1675],
        [0.3251, 0.9878, 0.7469, 0.7309],
        [0.5965, 0.8890, 0.7639, 0.0113]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


Manipulating tensors (tensor operations)

Tensor operations include: 
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [72]:
#create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor +  10


tensor([11, 12, 13])

In [73]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [74]:
tensor

tensor([1, 2, 3])

In [75]:
# subtract 10
tensor - 10

tensor([-9, -8, -7])

In [76]:
# try out pytorch inbuild functions
torch.mul(tensor,10)

tensor([10, 20, 30])

In [77]:
torch.add(tensor,10)

tensor([11, 12, 13])

Matrix multiplication

Two mian ways of performing multiplication in neural networks and deep learning:

1. element-wise multiplication
2. matrix multiplication (dot product)

there are two main rules that performing matrix multiplication needs to satisfy:
1. the **inner dimension** must match:
  `(3,2) @ (3,2)` wont work
  `(2,3) @ (3,2)` will work
  `(3,2) @ (2,3)` will work
2. The resulting matrix has the shape of the outer dimensions:
`(2,3) @ (3,2)` -> `(2,2)`
`(3,2) @ (2,3)` -> `(3,3)`

In [81]:
# element-wise multiplication
print(tensor,  "*" ,tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [82]:
torch.matmul(tensor, tensor)

tensor(14)

In [83]:
# matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [84]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 2.05 ms, sys: 7 µs, total: 2.05 ms
Wall time: 2.32 ms


tensor(14)

In [86]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 1.27 ms, sys: 0 ns, total: 1.27 ms
Wall time: 1.28 ms


tensor(14)

One of the most common errors in deep learning is shape errors

In [96]:
#Shapes for matrix multiplication
tensor_A = torch.tensor([[1,2], [3,4], [5,6]])
tensor_B = torch.tensor([[7,10], [8,11], [9,12]])

torch.mm(tensor_A, tensor_B.T) # torch.mm = torch.matmul


tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [97]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of. one of our tensors using Transpose

A **transpose** switches the axes or dimensions of a given tensor.

In [98]:
tensor_B.T.shape

torch.Size([2, 3])

In [99]:
tensor_B.shape

torch.Size([3, 2])

In [100]:
# The Matric mul operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = { tensor_B.shape}")
print(f"New shapes:: tensor_A = { tensor_A.shape} (Same shape as above), tensor_B.T= {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print('Output:\n')
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutpu shape: {output.shape}")



Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes:: tensor_A = torch.Size([3, 2]) (Same shape as above), tensor_B.T= torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Outpu shape: torch.Size([3, 3])


###Finding the min, max, mean, sum , etc(tensor aggregation)

In [112]:
#Create a tensor
x = torch.arange(1,100,10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [113]:
#Find the min
torch.min(x), x.min()

(tensor(1), tensor(1))

In [114]:
#Find the max
torch.max(x), x.max()

(tensor(91), tensor(91))

In [115]:
#Find the mean - note: torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [116]:
#Find the sum 
torch.sum(x) , x.sum()

(tensor(460), tensor(460))

###Finding the positional min and max

In [117]:
x


tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [118]:
#Find the position in tensor that has a minmum value with argmin() -> returns index positon of target tensor where min value occurs

x.argmin()

tensor(0)

In [119]:
x[0]

tensor(1)

In [120]:
#Find the position in tensor that has the maximum value with argmax()

x.argmax()

tensor(9)

In [121]:
x[9]

tensor(91)

###Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine mulitple tensors on top of eachother (vstack) or side-by-side(hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - adds a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted(swapped) in certain way

In [134]:
#Create a tensor 
import torch
x = torch.arange(1,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [135]:
#Add an extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [136]:
#Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [137]:
#Chnaging z chnages x (because a view of a tensor shares the smae memory as the original input)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [142]:
#Stack tensors on top of eachother
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [147]:
# torch.squeeze() - removes all single dimensions from a target tensor
print(f"Previoud tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

#remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_reshaped}")
print(f"New shape: {x_squeezed.shape}")

Previoud tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([9])


In [150]:
# torch.unsqueeze( )-> adds a single dimension to a target tensor at a specific dim 
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

#Add extra dimension
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [152]:
#torch.permute -  rearrange the dimension of the target tensor in a specified order

x_original = torch.rand(size=(224, 224, 3)) # height width color channels


#permute the original tensor to rearrange the axis or dimension order
x_permuted = x_original.permute(2, 0, 1) #shifts the axis 0->1 1->2 2->0
print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [154]:
x_original[0, 0, 0] = 34246

In [156]:
x_permuted[0,0,0]

tensor(34246.)

###Indexing (selecting data from tensors)

Indexing with pytorch is similar with Numpy.


In [157]:
#Create a tensor
import torch
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]), torch.Size([1, 3, 3]))

In [158]:
#index on the new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [160]:
#index on the middle bracket 
x[0, 0]

tensor([1, 2, 3])

In [165]:
#index on the most inner bracket (last dimension)
x[0][2][2]

tensor(9)

In [166]:
# can also use: ":" to select "all" of the target dimension
x[:, 0]


tensor([[1, 2, 3]])

In [167]:
#get all value sof 0th and first dimension but only index of 1 on 2nd dimension
x[:,:, 1]

tensor([[2, 5, 8]])

In [168]:
#get all values of 0 dimension bt only the 1 index value of the 1st and 2nd dimensions
x[:, 1, 1]

tensor([5])

In [169]:
#get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0,0,:]

tensor([1, 2, 3])

###Pytorch tensors and NumPy

NumPy is a popular scientific python numerical computing library

and because of this oytorch has the functionality to interract with it.

* Data in NumPy, want in PyTorch Tensor -> `torch.from_numpy(ndarray)`
* Pytorch tensor -> NumPy -> `torch.tensor.numpy()`

In [176]:
#NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [177]:
#Change the value of an array
array = array +1 
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [178]:
#tensor to numpy array

tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [180]:
#Chnage the tensor,  what happens to numpy?
tensor = tensor + 1
numpy_tensor, tensor

(array([1., 1., 1., 1., 1., 1., 1.], dtype=float32),
 tensor([2., 2., 2., 2., 2., 2., 2.]))

###Reproducability ( trying to take a random out of random)

Inshort how a neural network learn:

`start with random number -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> ...`

To reduce the randomness in neural networks and pytorch comes the concept of a **random seed**.

Essentially, the random seed "flavour" the randomness

In [181]:
import torch

#Create two random tensors 
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)


print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.5171, 0.2336, 0.0600, 0.2560],
        [0.7478, 0.8045, 0.9138, 0.3473],
        [0.5572, 0.4206, 0.5955, 0.5090]])
tensor([[0.4530, 0.9295, 0.6684, 0.4051],
        [0.7440, 0.7259, 0.9893, 0.7056],
        [0.9623, 0.5255, 0.7744, 0.6640]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [184]:
from IPython.lib.security import random
# make some random but reproducible tensors
import torch

#set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


###Running tensors and pytorch objects on the GPUs ( and making faster computations)

GPUs = faster computation on numbers, thanks to CUDA + Nvidia hardware + Pytorch working behind the scnes for running good

# 1. Getting a GPU

1. Easiest - google colab for free or pro
2. use own GPU -takes a little bit of setup and requires the investment of purchasing a GPU.
3. Use cloud computing - GCP, AWS ,Azure,  these services allow to rent computers on the cloud and access them.


For 2, 3 Pytorch +GPU drivers (CUDA) takes a bit of setting up. check out the pytorch doc.

In [1]:
!nvidia-smi

Wed Feb 15 18:08:15 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.47.03    Driver Version: 510.47.03    CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   64C    P0    21W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

###2. Check for GPU access with PyTorch

In [2]:
# check for the GPU access with pytorch
import torch
torch.cuda.is_available()

True

In [3]:
# setup device agnostic code
device = "cuda"if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [4]:
# count the number of devices
torch.cuda.device_count()

1

###3. Putting tensors and models on the GPU

The reason we want our tensors/models on the GPU is beacause using GPU results in faster computations

In [6]:
#Create a tensor (Default on the CPU)
tensor = torch.tensor([1,2,3])

#tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [7]:
#Move tensor to GPU if available 
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4.  Moving tensors back to the CPU

In [8]:
# if tensor is on GPU, cant transform it to NUmpy
tensor_on_gpu.numpy()

TypeError: ignored

In [9]:
# to fic the GPU tensor with numpy issue, we can first set it to the cpu
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [10]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

## Exercises and extra curriculum

All of the exercises are focused on practicing the code above.

You should be able to complete them by referencing each section or by following the resource(s) linked.

Resources:

Exercise template notebook for 00.
Example solutions notebook for 00 (try the exercises before looking at this).
Documentation reading - A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness). See the documentation on torch.Tensor and for torch.cuda.
Create a random tensor with shape (7, 7).
Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).
Set the random seed to 0 and do exercises 2 & 3 over again.
Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one). If there is, set the GPU random seed to 1234.
Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed).
Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).
Find the maximum and minimum values of the output of 7.
Find the maximum and minimum index values of the output of 7.
Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.
Extra-curriculum
Spend 1-hour going through the PyTorch basics tutorial (I'd recommend the Quickstart and Tensors sections).
To learn more on how a tensor can represent data, see this video: What's a tensor?
